language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
install:
  - "python setup.py install"
script: "nosetests --dataproviders-first --processes=1 tests/"
script: "lode_runner --dataproviders-first --processes=1 tests/"
